name: Setup Dart
description: Setup Dart

runs:
  using: composite
  steps:
    - name: Read .tool-versions
      uses: wasabeef/import-asdf-tool-versions-action@2049f3fd1a331dc40d2eda76c614c9bd7f1a502d # v1.0.3
      id: asdf

    - name: Setup Dart
      uses: dart-lang/setup-dart@e630b99d28a3b71860378cafdc2a067c71107f94 # v1.7.0
      with:
        sdk: ${{ steps.asdf.outputs.dart }}

    - name: Install Pubs
      run: dart pub get
      shell: bash
