name: GitHub App Token Workflow

on:
  workflow_dispatch:

jobs:
  generate-token:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v3

      - name: GitHub Appトークンの生成
        id: create_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.GITHUB_APP_ID }}
          private-key: ${{ secrets.GITHUB_APP_PRIVATE_KEY }}
      - name: 生成トークンの利用例
        run: "echo 'トークン: ${{ steps.create_token.outputs.token }}'"

