name: Simple Echo Workflow

on: [push, pull_request]

jobs:
  echo-job:
    runs-on: ubuntu-latest
    steps:
      - name: チェックアウトリポジトリ
        uses: actions/checkout@v3

      - name: Echo output
        run: |
          output="Hello, World!"
          echo $output
