name: Commit to Branch

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to commit to'
        required: true
        default: 'main'
      commit_message:
        description: 'The commit message'
        required: true
        default: 'Automated commit via GitHub Actions'

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Create a new commit
      run: |
        git checkout ${{ inputs.branch }}
        echo "Current date: $(date '+%Y-%m-%d')" >> changes.md
        git add changes.md
        git commit -m "${{ inputs.commit_message }}"

    - name: Push changes
      run: |
        git push origin ${{ inputs.branch }}
