name: リリースノート作成

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'リリースするタグ名（例：v1.0.0）'
        required: true
      release_name:
        description: 'リリース名（例：バージョン1.0.0）'
        required: true
      body:
        description: 'リリースノートの内容'
        required: false
      draft:
        description: 'ドラフトリリースとして作成する'
        type: boolean
        default: false
      prerelease:
        description: 'プレリリースとして作成する'
        type: boolean
        default: false

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v4

      - name: リリースノートの作成
        uses: ncipollo/release-action@440c8c1cb0ed28b9f43e4d1d670870f059653174 # v1.16.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.tag_name }}
          name: ${{ github.event.inputs.release_name }}
          body: ${{ github.event.inputs.body }}
          draft: ${{ github.event.inputs.draft }}
          prerelease: ${{ github.event.inputs.prerelease }}
          generateReleaseNotes: true
