name: Create Tag

on:
  pull_request:
    types: [labeled]

jobs:
  deploy-command:
    if: github.event.label.name == 'create-tag'
    runs-on: ubuntu-latest
    steps:

      - name: Set up Dart
        uses: ./.github/actions/setup-dart

      - name: Get version from pubspec.yaml
        id: pubspec
        shell: bash
        run: |
          # git checkout HEAD pubspec.yaml
          # show git branch name
          echo $(git branch --show-current)
          dart pub global activate cider
          echo "version=$(cider version)" >> "$GITHUB_OUTPUT"

      - run: echo ${{ steps.pubspec.outputs.version }}

      - name: Get latest release tag
        id: get-latest-tag
        run: |
          # Get the latest release tag (works even if the tag is not on main)
          latest_tag=$(git describe --abbrev=0 --tags "$(git rev-list --tags --max-count=1)")
          echo "tag=$latest_tag" >> "$GITHUB_OUTPUT"

      - name: Check if tag already exists
        id: check_tag
        run: |
          version="${{ steps.pubspec.outputs.version }}"
          if git tag --list | grep -q "$version"
          then
            echo "exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "exists=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Comment if tag already exists
        if: steps.check_tag.outputs.exists == 'true'
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "> [!WARNING]\n> [Tag ${{ steps.pubspec.outputs.version }}](https://github.com/techiro/release-test/tags) already exists. Please delete the tag and try again."
            })

      - name: Create new tag if it does not exist
        if: steps.check_tag.outputs.exists == 'false'
        run: |
          echo "Creating tag test: ${{ steps.pubspec.outputs.version }}"
          git tag "${{ steps.pubspec.outputs.version }}"
          git push origin "${{ steps.pubspec.outputs.version }}"
          echo "tag_created=true" >> "$GITHUB_OUTPUT"

      - name: Reply to PR comment
        if: steps.check_tag.outputs.exists == 'false'
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '> [!IMPORTANT]\n> [Tag ${{ steps.pubspec.outputs.version }}](https://github.com/techiro/release-test/tags) has been created.'
            })
