name: Matrix Build Demo
on: push
jobs:
  animal_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        animal: [ cat, dog, rabbit ]   # マトリクス変数の定義
    steps:
      - name: Print matrix value
        run: echo "Animal = ${{ matrix.animal }}"
