name: Secrets and Vars Demo
on: push
jobs:
  secrets_demo:
    runs-on: ubuntu-latest
    steps:
      - name: Print secret and variable
        env:
          DEMO_VAR_VAL: ${{ vars.DEMO_VAR }}         # リポジトリ変数から環境変数へ展開
          MY_SECRET_VAL: ${{ secrets.DEMO_SECRET }}    # シークレットから環境変数へ展開
        run: |
          echo "Repository var value = $DEMO_VAR_VAL"
          echo "Secret value         = $MY_SECRET_VAL"
