name: Download artifact

on:
  pull_request:

jobs:
  get-results:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all results
        uses: actions/download-artifact@v4
        with:
          path: .
      - name: Get Results
        run: ls -la
