name: Hotfix Workflow

on:
  workflow_dispatch:
    inputs:
      build_number:
        type: string
        required: false
        description: 'ビルドナンバーを指定'

jobs:
  create-hotfix-branch:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v3

      - name: 直近のリリースタグを取得
        id: get-latest-tag
        run: |
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "Latest tag: $latest_tag"
          echo "tag=$latest_tag" >> $GITHUB_OUTPUT

      - name: latest-tag-build_numberの取得
        id: get-build-number
        run: |
          latest_tag_build_number=$(echo ${{ steps.get-latest-tag.outputs.tag }} | sed -e 's/.*-//')
          echo "Latest tag build number: $latest_tag_build_number"
          echo "latest_tag_build_number=$latest_tag_build_number" >> $GITHUB_OUTPUT

      - name: ビルド番号の作成
        id: hotfix-build-number
        run: |
          build_number=${{ github.event.inputs.build_number }}
          if [ -z "$build_number" ]; then
            build_number=${{ steps.get-build-number.outputs.latest_tag_build_number }}
            echo "Build number is not specified. Use latest tag build number."
            build_number=$((build_number + 100))
          fi
          echo "Build number: $build_number"
          echo "build_number=$build_number" >> $GITHUB_OUTPUT

      - name: hotfixブランチの作成
        run: |
          # 一旦、すべての、latest_tag,latest_tag_build_number,build_numberを表示
          echo "latest_tag: ${{ steps.get-latest-tag.outputs.tag }}"
          echo "latest_tag_build_number: ${{ steps.get-build-number.outputs.latest_tag_build_number }}"
          echo "build_number: ${{ steps.hotfix-build-number.outputs.build_number }}"

