name: Hotfix Workflow

on:
  workflow_dispatch:
    inputs:
      build_number:
        type: string
        required: false
        description: 'ビルド番号を指定してください'

jobs:
  create-hotfix-branch:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: 最新のリリースタグを取得
        id: get-latest-tag
        run: |
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "Latest tag: $latest_tag"
          echo "tag=$latest_tag" >> $GITHUB_OUTPUT

      - name: 最新タグのビルド番号を取得
        id: get-build-number
        run: |
          latest_tag_build_number=$(echo ${{ steps.get-latest-tag.outputs.tag }} | sed -e 's/.*-//')
          echo "Latest tag build number: $latest_tag_build_number"
          echo "latest_tag_build_number=$latest_tag_build_number" >> $GITHUB_OUTPUT

      - name: ビルド番号を作成
        id: hotfix-build-number
        run: |
          build_number=${{ github.event.inputs.build_number }}
          if [ -z "$build_number" ]; then
            build_number=$((${{ steps.get-build-number.outputs.latest_tag_build_number }} + 100))
            echo "Build number is not specified. Using latest tag build number."
          fi
          echo "Build number: $build_number"
          echo "build_number=$build_number" >> $GITHUB_OUTPUT

      - name: ホットフィックスブランチを作成
        id: create-hotfix
        run: |
          branch_name="hotfix-${{ steps.get-latest-tag.outputs.tag }}"
          git checkout -b $branch_name ${{ steps.get-latest-tag.outputs.tag }}

      - name: pubspec のバージョンを更新する
        run: |
          cider bump patch --build=${{  steps.hotfix-build-number.outputs.build_number  }}
          sed -i -e '/^version:/ s/+/-/g' pubspec.yaml

      - name: コミットとプッシュ
        run: |
          git add pubspec.yaml
          git commit -m "Bump version for hotfix"
          git push --set-upstream origin ${{ steps.create-hotfix.outputs.branch_name }}

      - name: Setup Dart
        uses: ./.github/actions/setup-dart

      - name: Install cider
        run: dart pub global activate cider

