name: Hotfix Workflow

on:
  workflow_dispatch:
    inputs:
      build_number:
        type: string
        required: false
        description: 'ビルド番号を指定してください。指定がなければ、最新のビルド番号に100を加えたものが使用されます'
      target_branch:
        type: string
        required: false
        description: 'ホットフィックスを切る元のブランチを指定してください。指定がなければ、最新のリリースタグが使用されます'

permissions:
  contents: write

jobs:
  create-hotfix-branch:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 最新のリリースタグを取得
        id: get-latest-tag
        run: |
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "tag=$latest_tag" >> $GITHUB_OUTPUT

      - name: 既存ブランチを削除
        run: |
          check_branch_name="hotfix-from-${{ github.event.inputs.target_branch != '' && github.event.inputs.target_branch || steps.get-latest-tag.outputs.tag }}"

          existing_branch=$(git ls-remote --heads origin "$check_branch_name")
          if [ -n "$existing_branch" ]; then
            echo "$check_branch_name が存在していたので削除します。"
            git push origin --delete "$check_branch_name"
          else
            echo "既存のブランチはありません。"
          fi

      - name: ホットフィックスブランチを作成
        id: create-hotfix
        run: |
          branch_name="hotfix-from-${{ steps.get-latest-tag.outputs.tag }}"
          echo "switch from ${{ steps.get-latest-tag.outputs.tag }} to $branch_name"
          git checkout -b "$branch_name" ${{ steps.get-latest-tag.outputs.tag }}
          git push --set-upstream origin "$branch_name"
          echo "branch_name=$branch_name" >> $GITHUB_OUTPUT

      - name: ホットフィックスのビルド番号を取得
        id: hotfix-build-number
        run: |
          latest_tag_build_number=$(echo "${{ steps.get-latest-tag.outputs.tag }}" | sed -e 's/.*-//')
          build_number="${{ github.event.inputs.build_number }}"
          if [ -z "$build_number" ]; then
          build_number=$(( latest_tag_build_number + 100 ))
          echo "ビルド番号が指定されていません。計算されたビルド番号を使用します。"
          fi
          echo "latest_tag_build_number=$latest_tag_build_number" >> "$GITHUB_OUTPUT"
          echo "build_number=$build_number" >> "$GITHUB_OUTPUT"

      - name: Dartをセットアップする
        uses: ./.github/actions/setup-dart


      - name: バージョンをバンプする
        run: |
          dart pub global activate cider
          sed -i -E 's/version: ([0-9]+\.[0-9]+\.[0-9]+)-([0-9]+)/version: \1+\2/' pubspec.yaml
          cider bump patch --build=${{ steps.hotfix-build-number.outputs.build_number }}
          sed -i -E 's/version: ([0-9]+\.[0-9]+\.[0-9]+)\+([0-9]+)/version: \1-\2/' pubspec.yaml
          echo "bump_version=$(cider version)" >> "$GITHUB_OUTPUT"

      - name: 更新後のバージョンを取得して出力する
        id: bump-version
        run: |
          echo "pubspec_version=$(cider version | sed -e 's/.*-//')" >> "$GITHUB_OUTPUT"

      - name: Configure Git user
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add pubspec.yaml
          git status

      - name: コミットとプッシュ
        run: |
          git commit -m "Bump version for hotfix" || echo "No changes to commit"
          git push --set-upstream origin ${{ steps.create-hotfix.outputs.branch_name }}

      - name: Create PR
        env:
          GH_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
        run: |
          gh pr create \
            --draft \
            --base main \
            --head ${{ steps.create-hotfix.outputs.branch_name }} \
            --label "A-build" \
            --title "release: Hotfix ${{ steps.bump-version.outputs.pubspec_version}}" \
            --body-file "./pr-body/hotfix-pr-body.md"
