name: List Repository Files

on: workflow_dispatch

jobs:
  show-files:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: List files with ls
        run: |
          ls -laR

      # もしtreeコマンドを使いたい場合は下記のように追加
      - name: Install tree and list files
        run: |
          sudo apt-get update && sudo apt-get install -y tree
          tree -a
