name: Manual Dispatch Demo
on:
  workflow_dispatch:
    inputs:
      NAME:
        description: "Name for greeting"
        required: true
      VALUE:
        description: "Some value to print"
        required: false
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Show inputs
        run: echo "Hello ${{ github.event.inputs.NAME }}, VALUE = ${{ github.event.inputs.VALUE }}"
