name: Receive Server Updates

on:
  repository_dispatch:
    types: [server-update]

jobs:
  sync-server-resources:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Run sync command
        run: |
          make sync server-release

      - name: Check for changes
        id: git-check
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Create branch and commit changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          BRANCH_NAME="update-server-resources-$(date +%Y%m%d%H%M%S)"
          git checkout -b $BRANCH_NAME
          git add .
          git commit -m "Update server resources from release-test-server"
          git push origin $BRANCH_NAME

      - name: Create Pull Request
        if: steps.git-check.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Update server resources from release-test-server"
          body: |
            This PR contains updated resources from the release-test-server repository.
            
            Automatically generated by the server-update workflow.
          branch: ${{ env.BRANCH_NAME }}
          base: main
          draft: false