name: Skip Steps Demo
on: push
jobs:
  skip_example:
    runs-on: ubuntu-latest
    steps:
      - name: Always run
        run: echo "This step runs in any environment"
      - name: Run on GitHub only
        if: ${{ !env.ACT }}
        run: echo "This step runs on GitHub, but is skipped in act"
      - name: Run on act only
        if: ${{ env.ACT }}
        run: echo "This step runs only in local act run"
