name: Releases

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: リポジトリをチェックアウト
      uses: actions/checkout@v3
    - name: リリースを作成
      uses: ncipollo/release-action@v1
      with:
        bodyFile: "release-note-body.md"
